#+TITLE: World
#+PROPERTY: header-args :emacs-lisp :tangle yes :cache yes :results silent :comments link :exports code
#+AUTHOR: John Axel Eriksson
#+TOC: true
#+STARTUP: fninline overview

This is the [[https://nixos.org][NixOS]] configuration repository for all my machines and custom packages (i.e not part of [[https://github.com/nixos/nixpkgs][nixpkgs]] yet). In some sense it is my world, which is how it got its name.

It's based on a relatively recent feature of the [[https://nixos.org][Nix package manager]] called [[https://nixos.wiki/wiki/Flakes][flakes]]. Flakes are somewhat similar to a ~Cargo.toml/Cargo.lock~ from the [[https://rust-lang.org][Rust programming language]], a ~go.mod/go.sum~ from the [[https://golang.org/][Go programming language]] or the ~package.json/package.lock~ files used by the [[https://www.npmjs.com/][Node Package Manager]]. The difference being that it is language agnostic - it handles any package(s) or file(s) really. Here, we're using it to build hosts and software deterministically in a reproducible fashion. This would all be possible using Nix without the flakes feature, but it would be more work to design and keep it up-to-date. While flakes are still labelled "experimental" they have a bright future.

This repo is using [[https://flake.parts][flake-parts]] to modularize and clean up [[./flake.nix][./flake.nix]].

* Installing a new machine

Add a new toml file under the [[hosts/][hosts/]] directory, possibly copying an existing fitting host and modifying it. Add the wanted profiles and other configuration. Commit and push them to this repository.

** Running the installation process

Download a recent installer from [[https://nixos.org/download.html#nixos-iso][https://nixos.org/download.html#nixos-iso]] and enable flakes after booting it:

#+BEGIN_SRC sh
  mkdir -p /etc/nix
  cat<<EOF>>/etc/nix/nix.conf
  experimental-features = nix-command flakes
  EOF
#+END_SRC

Then proceed to clone this repo:

#+BEGIN_SRC sh
  cd /tmp
  git clone https://github.com/johnae/world
  cd world
#+END_SRC

After that, just pick the host you're installing, like this:

#+BEGIN_SRC sh
  host=eris
  nix build .#"$host"-diskformat
  ./result/bin/diskformat
  nixos-install --flake .#"$host" --no-root-passwd --impure
#+END_SRC

Hosts are defined in the [[hosts/][hosts/]] directory.

/This setup is very customized to my taste. For example: all disks are encrypted using dm-crypt and then on top of that formatted as btrfs, swap is automatically setup to a "reasonable" value that is not ideal for a lot of use cases, root is mounted as tmpfs and will therefore use some amount of RAM and it'll also be ephemeral - a reboot results in a clean slate and you'll have to opt-in to what you want to keep./

* Updating an existing machine

Updates should be handled through standard commit/push/pullreq workflow. Updating a machine called "andromeda" can be done like this (on that machine):

#+BEGIN_SRC sh
  nixos-rebuild switch --flake github:johnae/world#andromeda --use-remote-sudo
  ## in fact, you should be able to just do (because the hostname of the machine will be automatically chosen as default):
  nixos-rebuild switch --flake github:johnae/world --use-remote-sudo
#+END_SRC

or via a local clone of this repo:

#+BEGIN_SRC sh
  git clone git@github.com:johnae/world
  cd world
  nixos-rebuild switch --flake .#andromeda --use-remote-sudo
#+END_SRC

* Package updates etc

Package updates and OS updates are automated through actions. The update action creates pull requests where all custom packages are built and then all machine configurations are built to test that things seem ok before merging. This should catch many issues coming from OS and package updates before they're deployed.

* License
[[https://choosealicense.com/licenses/mit][MIT]]

This repository references many packages with varying licenses so please only consider the actual code in this repo to be MIT licensed.
