#!/usr/bin/env bash

set -euo pipefail

TF_VAR_kexec_tarball="$(nix build .#kexec-installer-nixos-unstable-noninteractive --print-out-paths --no-link)/nixos-kexec-installer-noninteractive-x86_64-linux.tar.gz"
export TF_VAR_kexec_tarball

tofu apply -auto-approve
sleep 5

IP="$(tofu output -raw dev_ip)"

function unlock() {
  retries=5
  while true; do
    if [ ${retries} -le 0 ]; then
      echo "Failed to unlock host"
      exit 1
    fi
    retries=$((retries - 1))
    echo "Probing host ${IP} on strPort 2222"
    if timeout 5 bash -c "</dev/tcp/${IP}/2222"; then
      echo "Host ${IP} is up, unlocking"
      rbw get hetzner -- cloud_disk_password | ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/john/.ssh/id_ed25519_alt -p 2222 "root@${IP}"
      break
    else
      echo "Host ${IP} is down, retrying unlock later"
    fi
    echo "Waiting 5 seconds..."
    sleep 5
  done
}

unlock
