#!/usr/bin/env bash

if [ "$(ssh-add -L | wc -l)" = "0" ]; then
  echo "Hey - you need to add your ssh key to the agent"
  exit 1
fi

tofu apply -auto-approve
sleep 10

unlocked_all=1

function unlock() {
  for server in $(hcloud server list -o noheader -l "tfstate=k3s" | awk '{print $4}'); do
    echo "Probing host ${server} on strPort 2222"
    if timeout 5 bash -c "</dev/tcp/${server}/2222"; then
      echo "Host ${server} is up, unlocking"
      rbw get hetzner -- cloud_disk_password | ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i /home/john/.ssh/id_ed25519_alt -p 2222 "root@${server}"
    else
      if timeout 5 bash -c "</dev/tcp/${server}/22"; then
        echo "Host ${server} is already unlocked"
      else
        unlocked_all=0
        echo "Host ${server} is down, retry later"
      fi
    fi
  done
}

unlock
if [[ ${unlocked_all} -eq 0 ]]; then
  echo "retrying unlocking in 10 seconds"
  sleep 10
  unlock
fi

CLUSTER_ID="$(tofu output --json | jq -r .k8s_api.value)"

echo configuring kubectl for "$CLUSTER_ID"
retries=10
while ! tailscale configure kubeconfig "$CLUSTER_ID"; do
  sleep 10
  retries=$((retries - 1))
  if [ "$retries" -le 0 ]; then
    echo giving up trying to configure kubectl
    exit 1
  fi
done

kubectl get pods --all-namespaces
