system = "x86_64-linux"

[config]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOteEiVr+H3Q1tSw1bGQfjbVWuPggc/+w1vVXSFde0Rt"
syncthingDeviceID = "53R5CPY-RVICTGR-AEXNKZU-RMCKC32-JNON7PH-4VEFCRB-KRPLP3M-AIEQPA6"

profiles = [
  "profiles/hardware/nuc",
  "profiles/default_fs",
  "profiles/hidpi",
  "profiles/k3s",
  "profiles/server",
  "profiles/state",
  "profiles/syncthing",
  "profiles/tailscale",
  "profiles/uuid_disk_crypt",
  "profiles/zram",
]


[config.system.autoUpgrade]
enable = true
flake = "github:johnae/world"
allowReboot = true
dates = "*:0/15"
randomizedDelaySec = "5min"
enableSentinel = true

[config.users.groups.john]
gid = 1337

[config.users.users.john]
uid = 1337
hashedPassword = "$6$6yT8x5V.3tTyRN2g$idNICkxytVFU6SR9DaafbU9W6.0qVdjyKMDzJCRWC/lwgjctxh4nFDCH2XHrEtb75WRsMFDGLJei0E3WiRqGz."
openssh.authorizedKeys.keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyjMuNOFrZBi7CrTyu71X+aRKyzvTmwCEkomhB0dEhENiQ3PTGVVWBi1Ta9E9fqbqTW0HmNL5pjGV+BU8j9mSi6VxLzJVUweuwQuvqgAi0chAJVPe0FSzft9M7mJoEq5DajuSiL7dSjXpqNFDk/WCDUBE9pELw+TXvxyQpFO9KZwiYCCNRQY6dCjrPJxGwG+JzX6l900GFrgOXQ3KYGk8vzep2Qp+iuH1yTgEowUICkb/9CmZhHQXSvq2gAtoOsGTd9DTyLOeVwZFJkTL/QW0AJNRszckGtYdA3ftCUNsTLSP/VqYN9EjxcMHQe4PGjkK7VLb59DQJFyRQqvPXiUyxNloHcu/sDuiKHIk/0qDLHlVn2xc5zkvzSqoQxoXx+P4dDbje1KHLY8E96gLe2Csu0ti+qsM5KEvgYgwWwm2g3IBlaWwgAtC0UWEzIuBPrAgPd5vi+V50ITIaIk6KIV7JPOubLUXaLS5KW77pWyi9PqAGOXj+DgTWoB3QeeZh7CGhPL5fAecYN7Pw734cULZpnw10Bi/jp4Nlq1AJDk8BwLUJbzZ8aexwMf78syjkHJBBrTOAxADUE02nWBQd0w4K5tl/a3UnBYWGyX8TD44046Swl/RY/69PxFvYcVRuF4eARI6OWojs1uhoR9WkO8eGgEsuxxECwNpWxR5gjKcgJQ==",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIJY3QSBIiRKN8/B3nHgCBDpauQBOftphOeuF2TaBHGQSAAAABHNzaDo=",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIAwJWtQ5ZU9U0szWzJ+/GH2uvXZ15u9lL0RdcHdsXM0VAAAABHNzaDo=",
]

[config.networking]
defaultGateway = "192.168.20.1"

[config.networking.firewall]
trustedInterfaces = [ "insane" ] ## trust the vpn mesh

[[config.networking.interfaces.eth0.ipv4.addresses]]
address = "192.168.20.142"
prefixLength = 24

[config.services.syncthing]
enable = true
user = "john"
group = "users"
openDefaultPorts = true
folders."/home/john/Sync".id = "sync"
folders."/home/john/Sync".devices = [
  "antares",
  "eris",
  "icarus",
  "polaris",
  "hyperion",
  "sirius"
]
cert = "/run/agenix/syncthing-cert"
key = "/run/agenix/syncthing-key"
dataDir = "/home/john/.local/share/syncthing-data"

[[config.services.remote-unlock]]
enable = true
host = "65.108.2.146"
port = 2222
identityFile = "/run/agenix/id_ed25519_remote_unlock"
passwordFile = "/run/agenix/remote-disk-password"

[[config.services.remote-unlock]]
enable = true
host = "65.108.233.47"
port = 2222
identityFile = "/run/agenix/id_ed25519_remote_unlock"
passwordFile = "/run/agenix/remote-disk-password"

[config.age.secrets]
k3s-token.file = "secrets/k3s/token.age"
ubnt-api-user-password.file = "secrets/ubnt-api-user-password.age"
wg-home.file = "secrets/titan/wg-home.age"
remote-disk-password.file = "secrets/remote-disk-password.age"
id_ed25519_remote_unlock.file = "secrets/titan/id_ed25519_remote_unlock.age"
syncthing-cert = { file = "secrets/titan/syncthing-cert.age", owner = "1337" }
syncthing-key = { file = "secrets/titan/syncthing-key.age", owner = "1337" }
tailscale-auth = { file = "secrets/tailscale-auth.age" }
ts-gh-9k = { file = "secrets/ts-gh-9k.age", owner = "1337" }

[config.services.tailscale.auth]
enable = true
args.advertise-tags = ["tag:server"]
args.ssh = true
args.accept-routes = false ## with this on, it causes issues in k3s when network runs on top of tailscale
args.auth-key = "file:/var/run/agenix/ts-gh-9k"

[config.services.k3s]
enable = true
role = "server"
after = [ "tailscale-auth.service" ]

[config.services.k3s.settings]
server = "https://polaris.tail7f302.ts.net:6443"
token-file = "/run/agenix/k3s-token"
flannel-iface = "tailscale0"
node-ip = "$(get-iface-ip tailscale0)"
node-external-ip = "$(get-iface-ip eth0)"
with-node-id = true
advertise-address = "$(get-iface-ip tailscale0)"
cluster-cidr = "10.128.128.0/21"
service-cidr = "10.129.128.0/22"
cluster-dns = "10.129.128.10"
kubelet-arg.max-pods = 62
kube-controller-manager-arg.node-cidr-mask-size = 25
kube-apiserver-arg.oidc-issuer-url = "https://id.9000.dev"
kube-apiserver-arg.oidc-username-claim = "email"
kube-apiserver-arg.oidc-groups-claim = "groups"
kube-apiserver-arg.oidc-client-id = "dex-auth"
node-label."topology.kubernetes.io/region" = "home"
node-label."topology.kubernetes.io/zone" = "home"
secrets-encryption = true
tls-san = "192.168.104.100"
